name: Gem

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GEM_NAME: orchestra

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec

  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    env:
      GEM_OWNER: ${{ github.repository_owner }}
      GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${GEM_OWNER} *.gem
